### ISSUE TITLE
log file is still generated after successful retry using plugin cypress-plugin-retries

### ISSUE THREAD

**Issue by takasoft** [bahmutov/cypress-failed-log#219]
Would be great if there's an option to not create log files in case retry is successful

**Comment by julianmendonca** [comment]
I am having the same issue, i was thinking about making that when the task succed, check if there is a file with that test error name and delete it. Since when the task fails it creates a json file with a specific error name, is it posible to do when a task is succesfull, check if there is a file with that error name (the one that would have if it had an error) and delete it?
